"""Comparison status constants (separate module to avoid import cycles)."""

OK = "OK"
MISMATCH = "MISMATCH"
MISSING_IN_INGEST = "MISSING_IN_INGEST"
MISSING_IN_DB = "MISSING_IN_DB"
SKIPPED = "SKIPPED"

# NRQL ingest-check statuses
INGEST_OK = "INGEST_OK"
INGEST_MISMATCH = "INGEST_MISMATCH"
INGEST_NO_DATA = "INGEST_NO_DATA"
INGEST_ERROR = "INGEST_ERROR"
INGEST_SKIPPED = "INGEST_SKIPPED"
